// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/data.proto

// See https://www.ibm.com/docs/en/zos-basic-skills?topic=layer-transmission-control-protocol-tcp

package datapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Series struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sets []*Set `protobuf:"bytes,1,rep,name=Sets,proto3" json:"Sets,omitempty"`
}

func (x *Series) Reset() {
	*x = Series{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *Series) GetSets() []*Set {
	if x != nil {
		return x.Sets
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    string   `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Points []*Point `protobuf:"bytes,2,rep,name=Points,proto3" json:"Points,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *Set) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Set) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Value     *Value `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Status    uint32 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Point) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Point) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//	*Value_Bool
	//	*Value_Int32
	//	*Value_Int64
	//	*Value_Uint32
	//	*Value_Uint64
	//	*Value_Float32
	//	*Value_Float64
	//	*Value_String_
	//	*Value_Bytes
	//	*Value_Object
	//	*Value_Array
	Variant isValue_Variant `protobuf_oneof:"Variant"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (m *Value) GetVariant() isValue_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *Value) GetBool() bool {
	if x, ok := x.GetVariant().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Value) GetInt32() int32 {
	if x, ok := x.GetVariant().(*Value_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *Value) GetInt64() int64 {
	if x, ok := x.GetVariant().(*Value_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *Value) GetUint32() uint32 {
	if x, ok := x.GetVariant().(*Value_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (x *Value) GetUint64() uint64 {
	if x, ok := x.GetVariant().(*Value_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (x *Value) GetFloat32() float32 {
	if x, ok := x.GetVariant().(*Value_Float32); ok {
		return x.Float32
	}
	return 0
}

func (x *Value) GetFloat64() float64 {
	if x, ok := x.GetVariant().(*Value_Float64); ok {
		return x.Float64
	}
	return 0
}

func (x *Value) GetString_() string {
	if x, ok := x.GetVariant().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Value) GetBytes() []byte {
	if x, ok := x.GetVariant().(*Value_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *Value) GetObject() *Object {
	if x, ok := x.GetVariant().(*Value_Object); ok {
		return x.Object
	}
	return nil
}

func (x *Value) GetArray() *Array {
	if x, ok := x.GetVariant().(*Value_Array); ok {
		return x.Array
	}
	return nil
}

type isValue_Variant interface {
	isValue_Variant()
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,1,opt,name=Bool,proto3,oneof"`
}

type Value_Int32 struct {
	// int32 Int8 = 2; // ?
	// int32 Int16 = 3; // ?
	Int32 int32 `protobuf:"varint,4,opt,name=Int32,proto3,oneof"`
}

type Value_Int64 struct {
	Int64 int64 `protobuf:"varint,5,opt,name=Int64,proto3,oneof"`
}

type Value_Uint32 struct {
	// uint32 Uint8 = 6; // ?
	// uint32 Uint16 = 7; // ?
	Uint32 uint32 `protobuf:"varint,8,opt,name=Uint32,proto3,oneof"`
}

type Value_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,9,opt,name=Uint64,proto3,oneof"`
}

type Value_Float32 struct {
	Float32 float32 `protobuf:"fixed32,10,opt,name=Float32,proto3,oneof"`
}

type Value_Float64 struct {
	Float64 float64 `protobuf:"fixed64,11,opt,name=Float64,proto3,oneof"`
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,12,opt,name=String,proto3,oneof"`
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,13,opt,name=Bytes,proto3,oneof"`
}

type Value_Object struct {
	Object *Object `protobuf:"bytes,14,opt,name=Object,proto3,oneof"`
}

type Value_Array struct {
	Array *Array `protobuf:"bytes,15,opt,name=Array,proto3,oneof"`
}

func (*Value_Bool) isValue_Variant() {}

func (*Value_Int32) isValue_Variant() {}

func (*Value_Int64) isValue_Variant() {}

func (*Value_Uint32) isValue_Variant() {}

func (*Value_Uint64) isValue_Variant() {}

func (*Value_Float32) isValue_Variant() {}

func (*Value_Float64) isValue_Variant() {}

func (*Value_String_) isValue_Variant() {}

func (*Value_Bytes) isValue_Variant() {}

func (*Value_Object) isValue_Variant() {}

func (*Value_Array) isValue_Variant() {}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueByName map[string]*Value `protobuf:"bytes,1,rep,name=ValueByName,proto3" json:"ValueByName,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *Object) GetValueByName() map[string]*Value {
	if x != nil {
		return x.ValueByName
	}
	return nil
}

type Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoolArray []bool `protobuf:"varint,1,rep,packed,name=BoolArray,proto3" json:"BoolArray,omitempty"`
	// repeated int32 Int8Array = 2; // ?
	// repeated int32 Int16Array = 3; // ?
	Int32Array []int32 `protobuf:"varint,4,rep,packed,name=Int32Array,proto3" json:"Int32Array,omitempty"`
	Int64Array []int64 `protobuf:"varint,5,rep,packed,name=Int64Array,proto3" json:"Int64Array,omitempty"`
	// repeated uint32 Uint8Array = 6; // ?
	// repeated uint32 Uint16Array = 7; // ?
	Uint32Array  []uint32  `protobuf:"varint,8,rep,packed,name=Uint32Array,proto3" json:"Uint32Array,omitempty"`
	Uint64Array  []uint64  `protobuf:"varint,9,rep,packed,name=Uint64Array,proto3" json:"Uint64Array,omitempty"`
	Float32Array []float32 `protobuf:"fixed32,10,rep,packed,name=Float32Array,proto3" json:"Float32Array,omitempty"`
	Float64Array []float64 `protobuf:"fixed64,11,rep,packed,name=Float64Array,proto3" json:"Float64Array,omitempty"`
	StringArray  []string  `protobuf:"bytes,12,rep,name=StringArray,proto3" json:"StringArray,omitempty"`
	BytesArray   [][]byte  `protobuf:"bytes,13,rep,name=BytesArray,proto3" json:"BytesArray,omitempty"`
	ObjectArray  []*Object `protobuf:"bytes,14,rep,name=ObjectArray,proto3" json:"ObjectArray,omitempty"`
	ArrayArray   []*Array  `protobuf:"bytes,15,rep,name=ArrayArray,proto3" json:"ArrayArray,omitempty"`
}

func (x *Array) Reset() {
	*x = Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *Array) GetBoolArray() []bool {
	if x != nil {
		return x.BoolArray
	}
	return nil
}

func (x *Array) GetInt32Array() []int32 {
	if x != nil {
		return x.Int32Array
	}
	return nil
}

func (x *Array) GetInt64Array() []int64 {
	if x != nil {
		return x.Int64Array
	}
	return nil
}

func (x *Array) GetUint32Array() []uint32 {
	if x != nil {
		return x.Uint32Array
	}
	return nil
}

func (x *Array) GetUint64Array() []uint64 {
	if x != nil {
		return x.Uint64Array
	}
	return nil
}

func (x *Array) GetFloat32Array() []float32 {
	if x != nil {
		return x.Float32Array
	}
	return nil
}

func (x *Array) GetFloat64Array() []float64 {
	if x != nil {
		return x.Float64Array
	}
	return nil
}

func (x *Array) GetStringArray() []string {
	if x != nil {
		return x.StringArray
	}
	return nil
}

func (x *Array) GetBytesArray() [][]byte {
	if x != nil {
		return x.BytesArray
	}
	return nil
}

func (x *Array) GetObjectArray() []*Object {
	if x != nil {
		return x.ObjectArray
	}
	return nil
}

func (x *Array) GetArrayArray() []*Array {
	if x != nil {
		return x.ArrayArray
	}
	return nil
}

var File_proto_data_proto protoreflect.FileDescriptor

var file_proto_data_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x27, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x53, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x04, 0x53, 0x65, 0x74,
	0x73, 0x22, 0x3c, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x23, 0x0a, 0x06, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22,
	0x60, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xc3, 0x02, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x42,
	0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x16, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x05, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x12, 0x18, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x55,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x55,
	0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33,
	0x32, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a,
	0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x26, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52,
	0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42, 0x09, 0x0a, 0x07,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x1a, 0x4b, 0x0a, 0x10, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x90, 0x03, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f,
	0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x09, 0x42,
	0x6f, 0x6f, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x55,
	0x69, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0b, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x02, 0x52, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x79, 0x74, 0x65, 0x73, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2e, 0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2b, 0x0a, 0x0a, 0x41, 0x72, 0x72, 0x61, 0x79, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x0a, 0x41, 0x72, 0x72, 0x61, 0x79, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x42, 0x14, 0x5a, 0x12, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData = file_proto_data_proto_rawDesc
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_proto_rawDescData)
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_data_proto_goTypes = []interface{}{
	(*Series)(nil), // 0: data.Series
	(*Set)(nil),    // 1: data.Set
	(*Point)(nil),  // 2: data.Point
	(*Value)(nil),  // 3: data.Value
	(*Object)(nil), // 4: data.Object
	(*Array)(nil),  // 5: data.Array
	nil,            // 6: data.Object.ValueByNameEntry
}
var file_proto_data_proto_depIdxs = []int32{
	1, // 0: data.Series.Sets:type_name -> data.Set
	2, // 1: data.Set.Points:type_name -> data.Point
	3, // 2: data.Point.Value:type_name -> data.Value
	4, // 3: data.Value.Object:type_name -> data.Object
	5, // 4: data.Value.Array:type_name -> data.Array
	6, // 5: data.Object.ValueByName:type_name -> data.Object.ValueByNameEntry
	4, // 6: data.Array.ObjectArray:type_name -> data.Object
	5, // 7: data.Array.ArrayArray:type_name -> data.Array
	3, // 8: data.Object.ValueByNameEntry.value:type_name -> data.Value
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Series); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_data_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Value_Bool)(nil),
		(*Value_Int32)(nil),
		(*Value_Int64)(nil),
		(*Value_Uint32)(nil),
		(*Value_Uint64)(nil),
		(*Value_Float32)(nil),
		(*Value_Float64)(nil),
		(*Value_String_)(nil),
		(*Value_Bytes)(nil),
		(*Value_Object)(nil),
		(*Value_Array)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_rawDesc = nil
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
