// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcClient interface {
	Socket(ctx context.Context, opts ...grpc.CallOption) (Grpc_SocketClient, error)
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type grpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcClient(cc grpc.ClientConnInterface) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Socket(ctx context.Context, opts ...grpc.CallOption) (Grpc_SocketClient, error) {
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[0], "/grpc.Grpc/Socket", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcSocketClient{stream}
	return x, nil
}

type Grpc_SocketClient interface {
	Send(*SocketMessage) error
	Recv() (*SocketMessage, error)
	grpc.ClientStream
}

type grpcSocketClient struct {
	grpc.ClientStream
}

func (x *grpcSocketClient) Send(m *SocketMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcSocketClient) Recv() (*SocketMessage, error) {
	m := new(SocketMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, "/grpc.Grpc/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcServer is the server API for Grpc service.
// All implementations must embed UnimplementedGrpcServer
// for forward compatibility
type GrpcServer interface {
	Socket(Grpc_SocketServer) error
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedGrpcServer()
}

// UnimplementedGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcServer struct {
}

func (UnimplementedGrpcServer) Socket(Grpc_SocketServer) error {
	return status.Errorf(codes.Unimplemented, "method Socket not implemented")
}
func (UnimplementedGrpcServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedGrpcServer) mustEmbedUnimplementedGrpcServer() {}

// UnsafeGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServer will
// result in compilation errors.
type UnsafeGrpcServer interface {
	mustEmbedUnimplementedGrpcServer()
}

func RegisterGrpcServer(s grpc.ServiceRegistrar, srv GrpcServer) {
	s.RegisterService(&Grpc_ServiceDesc, srv)
}

func _Grpc_Socket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).Socket(&grpcSocketServer{stream})
}

type Grpc_SocketServer interface {
	Send(*SocketMessage) error
	Recv() (*SocketMessage, error)
	grpc.ServerStream
}

type grpcSocketServer struct {
	grpc.ServerStream
}

func (x *grpcSocketServer) Send(m *SocketMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcSocketServer) Recv() (*SocketMessage, error) {
	m := new(SocketMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Grpc_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Grpc/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grpc_ServiceDesc is the grpc.ServiceDesc for Grpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Grpc_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Socket",
			Handler:       _Grpc_Socket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/grpc.proto",
}
